---
HOSTS:
  el8:
    roles:
    - client
    platform: el-8-x86_64
    box: almalinux/8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: almalinux-cloud/almalinux-8
    gce_machine_type: n1-standard-2
  el9:
    roles:
    - client
    platform: el-9-x86_64
    box: almalinux/9
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: almalinux-cloud/almalinux-9
    gce_machine_type: n1-standard-2
  el10:
    roles:
    - client
    platform: el-10-x86_64
    box: almalinux/10
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  synced_folder: disabled
  type: aio
  vagrant_memsize: 512
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'openvox8') %>"
